# Your Turn! 

Find the file `experiment_data_small.csv` in the current working directory and run a t-test on this data.

* First report the p value of the test
* Second, write a statement on what the p value means
* Third, use the function from above to calculate the effect size
* Fourth, write a paragraph reccomending if we should adopt the change made by the second AB test we have run!

Be prepared to be assigned to a side where you advocate for adopting the new change or not adopting the new change!

In [1]:
import numpy as np
import pandas as pd
import statsmodels as sm
from statsmodels.stats.power import TTestIndPower
from statsmodels.stats.weightstats import ttest_ind
import math

df = pd.read_csv("experiment_data_small.csv")
df

    Unnamed: 0  baseline_small  experiment_small
0            1        4.089394          5.506201
1            2       10.884680         26.349077
2            3       17.741562        -18.941091
3            4       10.170520         33.235422
4            5        8.978086          8.503653
5            6      -20.621040         50.846111
6            7        3.883918         -2.098413
7            8       14.992028         -9.933039
8            9      -10.574880        -10.766133
9           10       10.721469         -2.557150
10          11      -17.272820         17.218844
11          12       -2.514974        -12.620420
12          13      -14.920290          2.991752
13          14      -10.579953         18.024367
14          15       -3.701603         10.731711
15          16        5.424743          5.560811
16          17        9.443861         16.118309
17          18       10.828140         -5.946411
18          19        8.864015         17.182336
19          20      -17.838114          0.222653
20          21       -1.122810         13.455463
21          22      -26.183781         40.919271
22          23        5.716167        -12.926869
23          24      -10.192887         -3.868965
24          25      -11.715383         -2.172089
25          26        7.454973          6.540288
26          27       -6.388284        -10.516211
27          28       -6.196274         -1.578381
28          29       15.645880         14.070556
29          30        3.240386         -8.215227

In [2]:
mu_1 = df['baseline_small'].mean()
mu_2 = df['experiment_small'].mean()

sigma_1 = df['baseline_small'].std()
sigma_2 = df['experiment_small'].std()

pool_sigma = math.sqrt(((sigma_1**2 + sigma_2**2)/2))

pool_sigma

14.42780381651844

In [4]:
def cohen_d(mean_1, mean_2, pooled_sd):
    diff = (mean_1 - mean_2)
    cohen_d = diff/pooled_sd
    return(cohen_d)

cohen_d(mu_1, mu_2, pool_sigma)

-0.45532385494817446

In [3]:
# Set Parameters 


effect = .45
alpha = .05
power = .9

# Perform Power Analysis
analysis = TTestIndPower()
result = analysis.solve_power(effect, power=power, nobs1=None, ratio=1.0, alpha=alpha)
print('Sample Size: %.3f' % result)

Sample Size: 104.747

In [4]:
big_test = sm.stats.weightstats.ttest_ind(df['baseline_small'], 
                               df['experiment_small'], 
                               alternative='two-sided', 
                               usevar='pooled', value=0)
                                                          
                                                          
print("The critical value is:", big_test[0])
print("The p value value is:", big_test[1])                                                          
print("Degrees of Freedom:", big_test[2])

The critical value is: -1.7634617073452414
The p value value is: 0.08308969146581927
Degrees of Freedom: 58.0